version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes: 
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment: 
      - POSTGRES_USER=reitor
      - POSTGRES_PASSWORD=reitor123
      - POSTGRES_DB=university