# Generated by Django 2.2.1 on 2019-05-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('nameCourse', models.CharField(max_length=45)),
                ('descriptionCourse', models.TextField()),
            ],
        ),
    ]
