# Generated by Django 2.2.1 on 2019-05-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('idMatter', models.AutoField(primary_key=True, serialize=False)),
                ('nameMatter', models.CharField(max_length=32)),
                ('descriptionMatter', models.TextField()),
                ('numberStudent', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Course')),
            ],
        ),
    ]
