# Generated by Django 2.2.1 on 2019-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='descriptionCourse',
            field=models.TextField(),
        ),
    ]
