# Generated by Django 2.2.1 on 2019-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_matter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idStudent', models.AutoField(primary_key=True, serialize=False)),
                ('nameStudent', models.CharField(max_length=32)),
                ('matter', models.ManyToManyField(to='curso.Matter')),
            ],
        ),
    ]
