# Generated by Django 2.2.1 on 2019-05-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_matter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.Course'),
        ),
    ]
