# Generated by Django 2.2.1 on 2019-05-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('idTeacher', models.AutoField(primary_key=True, serialize=False)),
                ('nameTeacher', models.CharField(max_length=64)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.Matter')),
            ],
        ),
    ]
