# Generated by Django 2.2.1 on 2019-05-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20190528_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Course'),
        ),
    ]
