# Generated by Django 2.2.1 on 2019-05-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matter',
        ),
    ]
