# Generated by Django 2.2.1 on 2019-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_remove_student_matter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='descriptionMatter',
            field=models.TextField(help_text='Uma breve descrição da ementa'),
        ),
        migrations.AlterField(
            model_name='matter',
            name='nameMatter',
            field=models.CharField(help_text='Nome da Matéria', max_length=32),
        ),
        migrations.AlterField(
            model_name='matter',
            name='numberStudent',
            field=models.IntegerField(help_text='O máximo de alunos por turma'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nameStudent',
            field=models.CharField(help_text='Nome do Aluno', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nameTeacher',
            field=models.CharField(help_text='Nome do Professor', max_length=64),
        ),
    ]
