# Generated by Django 2.2.1 on 2019-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_auto_20190601_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthasmatter',
            name='note',
        ),
    ]
